[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.8.8", features = [ "os-poll", "net" ] }
anyhow = "1.0"
slab = "0.4"
bytes = "0.5"
